package com.bean;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLeaveMsg implements java.io.Serializable
{
	private Integer id;//留言ID
	private String content;//留言内容
	private String leaveMsgTime;//留言时间
	private String user_id;//用户ID

	private String reply;//回复内容
	private String replyTime;//回复时间
	
	private Tuser user;

	public void SetAttribute(String content, String leaveMsgTime, String user_id, String reply, String replyTime) {
		setContent(content);
		setLeaveMsgTime(leaveMsgTime);
		setUser_id(user_id);
		setReply(replyTime);
		setReplyTime(replyTime);
	}

	public TLeaveMsg() {
		
	}

	public Integer getId()//得到回复ID
	{
		return id;
	}

	public void setId(Integer id)//设置回复ID
	{
		this.id = id;
	}

	public Tuser getUser()//得到留言用户
	{
		return user;
	}

	public void setUser(Tuser user)//设置留言用户
	{
		this.user = user;
	}

	public String getUser_id()//得到留言用户ID
	{
		return user_id;
	}

	public void setUser_id(String user_id)//设置留言用户ID
	{
		this.user_id = user_id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getLeaveMsgTime() {
		return leaveMsgTime;
	}

	public void setLeaveMsgTime(String leaveMsgTime) {
		this.leaveMsgTime = leaveMsgTime;
	}

	public String getReply() {
		return reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getReplyTime() {
		return replyTime;
	}

	public void setReplyTime(String replyTime) {
		this.replyTime = replyTime;
	}

	
}