package com.bean;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class Torder implements java.io.Serializable
{

	private String id;//订单ID
	private String showId;//订单编号
	private String time;//下单时间
	private String status;//订单状态
	
	private String reply;//回复内容
	
	private String deliveryAddress;//送货地址
	private String paymentMethod;//付款方式
	private int amount=0;//总金额
	private String user_id;//用户ID

	

	/** 默认构造函数 */
	public Torder()
	{
	}

	public String getId()//得到订单ID
	{
		return id;
	}

	public void setId(String id)//设置订单ID
	{
		this.id = id;
	}

	public String getUser_id()//得到用户ID
	{
		return user_id;
	}

	public void setUser_id(String user_id)//设置用户ID
	{
		this.user_id = user_id;
	}

	public String getShowId() {
		return showId;
	}

	public void setShowId(String showId) {
		this.showId = showId;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReply() {
		return reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getDeliveryAddress() {
		return deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public String getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	
}